version: 2.1

orbs:
  kube: circleci/kubernetes@0.11.0

commands:
  setup_ruby:
    steps:
      - checkout
      - run: |
          gem install bundler
      - run: |
          bundle update --bundler

jobs:
  test-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
      - image: mongo:4.1.4-xenial
    steps:
      - run: |
          mkdir /tmp/test-results
      - run: |
          mkdir -p /tmp/test-results/rspec
      - setup_ruby
      - run: |
          bundle exec rspec \
          --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml \
          --format html --out /tmp/html-results/results.html \
          --format progress spec/
      - store_test_results:
          path: /tmp/test-results/rspec
      - store_artifacts:
          path: /tmp/html-results
          destination: results
  doc-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - run: |
          mkdir /tmp/accounts
      - setup_ruby
      - run: |
          bundle exec yard doc -o /tmp/accounts controllers/ decorators/ services/
      - store_test_results:
          path: /tmp/accounts
      - store_artifacts:
          path: /tmp/accounts
          destination: accounts
  rubocop-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - run: |
          mkdir /tmp/accounts
      - setup_ruby
      - run: |
          bundle exec rubocop -F -f h -o /tmp/accounts/results.html controllers/ decorators/ services/
      - store_test_results:
          path: /tmp/accounts
      - store_artifacts:
          path: /tmp/accounts
          destination: accounts
  deploy-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - kube/install-kubectl
      - run: |
          echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
      - run: |
          gem install virtuatable
      - run: |
          virtuatable docker create accounts
      - run: |
          mkdir $HOME/.kube
      - run: |
          echo -n "${KUBERNETES_CONFIG}" | base64 --decode > $HOME/.kube/config
      - run: |
          gem install virtuatable
      - run: |
          virtuatable kube create accounts

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - rubocop-job
      - test-job:
          requires:
            - rubocop-job
      - doc-job:
          requires:
            - rubocop-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master